// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: app/src/main/proto/bb_log_entry.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.lohmegalog.protobuf;

@kotlin.jvm.JvmName("-initializebbLogEntry")
public inline fun bbLogEntry(block: bb_log_entryKt.Dsl.() -> kotlin.Unit): BbLogEntry.bb_log_entry =
  bb_log_entryKt.Dsl._create(BbLogEntry.bb_log_entry.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.example.lohmegalog.bb_log_entry`
 */
public object bb_log_entryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: BbLogEntry.bb_log_entry.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: BbLogEntry.bb_log_entry.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): BbLogEntry.bb_log_entry = _builder.build()

    /**
     * `required uint32 timestamp = 1;`
     */
    public var timestamp: kotlin.Int
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * `required uint32 timestamp = 1;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `required uint32 timestamp = 1;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    /**
     * `optional sint32 pressure = 2;`
     */
    public var pressure: kotlin.Int
      @JvmName("getPressure")
      get() = _builder.getPressure()
      @JvmName("setPressure")
      set(value) {
        _builder.setPressure(value)
      }
    /**
     * `optional sint32 pressure = 2;`
     */
    public fun clearPressure() {
      _builder.clearPressure()
    }
    /**
     * `optional sint32 pressure = 2;`
     * @return Whether the pressure field is set.
     */
    public fun hasPressure(): kotlin.Boolean {
      return _builder.hasPressure()
    }

    /**
     * `optional sint32 uvi = 3;`
     */
    public var uvi: kotlin.Int
      @JvmName("getUvi")
      get() = _builder.getUvi()
      @JvmName("setUvi")
      set(value) {
        _builder.setUvi(value)
      }
    /**
     * `optional sint32 uvi = 3;`
     */
    public fun clearUvi() {
      _builder.clearUvi()
    }
    /**
     * `optional sint32 uvi = 3;`
     * @return Whether the uvi field is set.
     */
    public fun hasUvi(): kotlin.Boolean {
      return _builder.hasUvi()
    }

    /**
     * `optional sint32 lux = 4;`
     */
    public var lux: kotlin.Int
      @JvmName("getLux")
      get() = _builder.getLux()
      @JvmName("setLux")
      set(value) {
        _builder.setLux(value)
      }
    /**
     * `optional sint32 lux = 4;`
     */
    public fun clearLux() {
      _builder.clearLux()
    }
    /**
     * `optional sint32 lux = 4;`
     * @return Whether the lux field is set.
     */
    public fun hasLux(): kotlin.Boolean {
      return _builder.hasLux()
    }

    /**
     * `optional sint32 rh = 5;`
     */
    public var rh: kotlin.Int
      @JvmName("getRh")
      get() = _builder.getRh()
      @JvmName("setRh")
      set(value) {
        _builder.setRh(value)
      }
    /**
     * `optional sint32 rh = 5;`
     */
    public fun clearRh() {
      _builder.clearRh()
    }
    /**
     * `optional sint32 rh = 5;`
     * @return Whether the rh field is set.
     */
    public fun hasRh(): kotlin.Boolean {
      return _builder.hasRh()
    }

    /**
     * `optional sint32 temperature = 6;`
     */
    public var temperature: kotlin.Int
      @JvmName("getTemperature")
      get() = _builder.getTemperature()
      @JvmName("setTemperature")
      set(value) {
        _builder.setTemperature(value)
      }
    /**
     * `optional sint32 temperature = 6;`
     */
    public fun clearTemperature() {
      _builder.clearTemperature()
    }
    /**
     * `optional sint32 temperature = 6;`
     * @return Whether the temperature field is set.
     */
    public fun hasTemperature(): kotlin.Boolean {
      return _builder.hasTemperature()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CompassProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated sint32 compass = 7;`
     */
     public val compass: com.google.protobuf.kotlin.DslList<kotlin.Int, CompassProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getCompassList()
      )
    /**
     * `repeated sint32 compass = 7;`
     * @param value The compass to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addCompass")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, CompassProxy>.add(value: kotlin.Int) {
      _builder.addCompass(value)
    }/**
     * `repeated sint32 compass = 7;`
     * @param value The compass to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignCompass")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, CompassProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * `repeated sint32 compass = 7;`
     * @param values The compass to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllCompass")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, CompassProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllCompass(values)
    }/**
     * `repeated sint32 compass = 7;`
     * @param values The compass to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllCompass")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, CompassProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * `repeated sint32 compass = 7;`
     * @param index The index to set the value at.
     * @param value The compass to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setCompass")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, CompassProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setCompass(index, value)
    }/**
     * `repeated sint32 compass = 7;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearCompass")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, CompassProxy>.clear() {
      _builder.clearCompass()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AccelerometerProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated sint32 accelerometer = 8;`
     */
     public val accelerometer: com.google.protobuf.kotlin.DslList<kotlin.Int, AccelerometerProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getAccelerometerList()
      )
    /**
     * `repeated sint32 accelerometer = 8;`
     * @param value The accelerometer to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAccelerometer")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, AccelerometerProxy>.add(value: kotlin.Int) {
      _builder.addAccelerometer(value)
    }/**
     * `repeated sint32 accelerometer = 8;`
     * @param value The accelerometer to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAccelerometer")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, AccelerometerProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * `repeated sint32 accelerometer = 8;`
     * @param values The accelerometer to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAccelerometer")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, AccelerometerProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllAccelerometer(values)
    }/**
     * `repeated sint32 accelerometer = 8;`
     * @param values The accelerometer to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAccelerometer")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, AccelerometerProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * `repeated sint32 accelerometer = 8;`
     * @param index The index to set the value at.
     * @param value The accelerometer to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAccelerometer")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, AccelerometerProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setAccelerometer(index, value)
    }/**
     * `repeated sint32 accelerometer = 8;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAccelerometer")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, AccelerometerProxy>.clear() {
      _builder.clearAccelerometer()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class GyroProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated sint32 gyro = 9;`
     */
     public val gyro: com.google.protobuf.kotlin.DslList<kotlin.Int, GyroProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getGyroList()
      )
    /**
     * `repeated sint32 gyro = 9;`
     * @param value The gyro to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addGyro")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, GyroProxy>.add(value: kotlin.Int) {
      _builder.addGyro(value)
    }/**
     * `repeated sint32 gyro = 9;`
     * @param value The gyro to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignGyro")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, GyroProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * `repeated sint32 gyro = 9;`
     * @param values The gyro to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllGyro")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, GyroProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllGyro(values)
    }/**
     * `repeated sint32 gyro = 9;`
     * @param values The gyro to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllGyro")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, GyroProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * `repeated sint32 gyro = 9;`
     * @param index The index to set the value at.
     * @param value The gyro to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setGyro")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, GyroProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setGyro(index, value)
    }/**
     * `repeated sint32 gyro = 9;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearGyro")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, GyroProxy>.clear() {
      _builder.clearGyro()
    }
    /**
     * ```
     *repeated float mpu9520_quaternion = 10;
     * ```
     *
     * `optional sint32 battery_mv = 11;`
     */
    public var batteryMv: kotlin.Int
      @JvmName("getBatteryMv")
      get() = _builder.getBatteryMv()
      @JvmName("setBatteryMv")
      set(value) {
        _builder.setBatteryMv(value)
      }
    /**
     * ```
     *repeated float mpu9520_quaternion = 10;
     * ```
     *
     * `optional sint32 battery_mv = 11;`
     */
    public fun clearBatteryMv() {
      _builder.clearBatteryMv()
    }
    /**
     * ```
     *repeated float mpu9520_quaternion = 10;
     * ```
     *
     * `optional sint32 battery_mv = 11;`
     * @return Whether the batteryMv field is set.
     */
    public fun hasBatteryMv(): kotlin.Boolean {
      return _builder.hasBatteryMv()
    }

    /**
     * `optional sint32 gpio0_mv = 12;`
     */
    public var gpio0Mv: kotlin.Int
      @JvmName("getGpio0Mv")
      get() = _builder.getGpio0Mv()
      @JvmName("setGpio0Mv")
      set(value) {
        _builder.setGpio0Mv(value)
      }
    /**
     * `optional sint32 gpio0_mv = 12;`
     */
    public fun clearGpio0Mv() {
      _builder.clearGpio0Mv()
    }
    /**
     * `optional sint32 gpio0_mv = 12;`
     * @return Whether the gpio0Mv field is set.
     */
    public fun hasGpio0Mv(): kotlin.Boolean {
      return _builder.hasGpio0Mv()
    }

    /**
     * `optional sint32 gpio1_mv = 13;`
     */
    public var gpio1Mv: kotlin.Int
      @JvmName("getGpio1Mv")
      get() = _builder.getGpio1Mv()
      @JvmName("setGpio1Mv")
      set(value) {
        _builder.setGpio1Mv(value)
      }
    /**
     * `optional sint32 gpio1_mv = 13;`
     */
    public fun clearGpio1Mv() {
      _builder.clearGpio1Mv()
    }
    /**
     * `optional sint32 gpio1_mv = 13;`
     * @return Whether the gpio1Mv field is set.
     */
    public fun hasGpio1Mv(): kotlin.Boolean {
      return _builder.hasGpio1Mv()
    }

    /**
     * `optional bool int_gpio0 = 14;`
     */
    public var intGpio0: kotlin.Boolean
      @JvmName("getIntGpio0")
      get() = _builder.getIntGpio0()
      @JvmName("setIntGpio0")
      set(value) {
        _builder.setIntGpio0(value)
      }
    /**
     * `optional bool int_gpio0 = 14;`
     */
    public fun clearIntGpio0() {
      _builder.clearIntGpio0()
    }
    /**
     * `optional bool int_gpio0 = 14;`
     * @return Whether the intGpio0 field is set.
     */
    public fun hasIntGpio0(): kotlin.Boolean {
      return _builder.hasIntGpio0()
    }

    /**
     * `optional bool int_gpio1 = 15;`
     */
    public var intGpio1: kotlin.Boolean
      @JvmName("getIntGpio1")
      get() = _builder.getIntGpio1()
      @JvmName("setIntGpio1")
      set(value) {
        _builder.setIntGpio1(value)
      }
    /**
     * `optional bool int_gpio1 = 15;`
     */
    public fun clearIntGpio1() {
      _builder.clearIntGpio1()
    }
    /**
     * `optional bool int_gpio1 = 15;`
     * @return Whether the intGpio1 field is set.
     */
    public fun hasIntGpio1(): kotlin.Boolean {
      return _builder.hasIntGpio1()
    }

    /**
     * `optional bool int_acc = 16;`
     */
    public var intAcc: kotlin.Boolean
      @JvmName("getIntAcc")
      get() = _builder.getIntAcc()
      @JvmName("setIntAcc")
      set(value) {
        _builder.setIntAcc(value)
      }
    /**
     * `optional bool int_acc = 16;`
     */
    public fun clearIntAcc() {
      _builder.clearIntAcc()
    }
    /**
     * `optional bool int_acc = 16;`
     * @return Whether the intAcc field is set.
     */
    public fun hasIntAcc(): kotlin.Boolean {
      return _builder.hasIntAcc()
    }
  }
}

