// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/src/main/proto/bb_log_entry.proto

package com.example.lohmegalog.protobuf;

public final class BbLogEntry {
  private BbLogEntry() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface bb_log_entryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.lohmegalog.bb_log_entry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>required uint32 timestamp = 1;</code>
     * @return The timestamp.
     */
    int getTimestamp();

    /**
     * <code>optional sint32 pressure = 2;</code>
     * @return Whether the pressure field is set.
     */
    boolean hasPressure();
    /**
     * <code>optional sint32 pressure = 2;</code>
     * @return The pressure.
     */
    int getPressure();

    /**
     * <code>optional sint32 uvi = 3;</code>
     * @return Whether the uvi field is set.
     */
    boolean hasUvi();
    /**
     * <code>optional sint32 uvi = 3;</code>
     * @return The uvi.
     */
    int getUvi();

    /**
     * <code>optional sint32 lux = 4;</code>
     * @return Whether the lux field is set.
     */
    boolean hasLux();
    /**
     * <code>optional sint32 lux = 4;</code>
     * @return The lux.
     */
    int getLux();

    /**
     * <code>optional sint32 rh = 5;</code>
     * @return Whether the rh field is set.
     */
    boolean hasRh();
    /**
     * <code>optional sint32 rh = 5;</code>
     * @return The rh.
     */
    int getRh();

    /**
     * <code>optional sint32 temperature = 6;</code>
     * @return Whether the temperature field is set.
     */
    boolean hasTemperature();
    /**
     * <code>optional sint32 temperature = 6;</code>
     * @return The temperature.
     */
    int getTemperature();

    /**
     * <code>repeated sint32 compass = 7;</code>
     * @return A list containing the compass.
     */
    java.util.List<java.lang.Integer> getCompassList();
    /**
     * <code>repeated sint32 compass = 7;</code>
     * @return The count of compass.
     */
    int getCompassCount();
    /**
     * <code>repeated sint32 compass = 7;</code>
     * @param index The index of the element to return.
     * @return The compass at the given index.
     */
    int getCompass(int index);

    /**
     * <code>repeated sint32 accelerometer = 8;</code>
     * @return A list containing the accelerometer.
     */
    java.util.List<java.lang.Integer> getAccelerometerList();
    /**
     * <code>repeated sint32 accelerometer = 8;</code>
     * @return The count of accelerometer.
     */
    int getAccelerometerCount();
    /**
     * <code>repeated sint32 accelerometer = 8;</code>
     * @param index The index of the element to return.
     * @return The accelerometer at the given index.
     */
    int getAccelerometer(int index);

    /**
     * <code>repeated sint32 gyro = 9;</code>
     * @return A list containing the gyro.
     */
    java.util.List<java.lang.Integer> getGyroList();
    /**
     * <code>repeated sint32 gyro = 9;</code>
     * @return The count of gyro.
     */
    int getGyroCount();
    /**
     * <code>repeated sint32 gyro = 9;</code>
     * @param index The index of the element to return.
     * @return The gyro at the given index.
     */
    int getGyro(int index);

    /**
     * <pre>
     *repeated float mpu9520_quaternion = 10;
     * </pre>
     *
     * <code>optional sint32 battery_mv = 11;</code>
     * @return Whether the batteryMv field is set.
     */
    boolean hasBatteryMv();
    /**
     * <pre>
     *repeated float mpu9520_quaternion = 10;
     * </pre>
     *
     * <code>optional sint32 battery_mv = 11;</code>
     * @return The batteryMv.
     */
    int getBatteryMv();

    /**
     * <code>optional sint32 gpio0_mv = 12;</code>
     * @return Whether the gpio0Mv field is set.
     */
    boolean hasGpio0Mv();
    /**
     * <code>optional sint32 gpio0_mv = 12;</code>
     * @return The gpio0Mv.
     */
    int getGpio0Mv();

    /**
     * <code>optional sint32 gpio1_mv = 13;</code>
     * @return Whether the gpio1Mv field is set.
     */
    boolean hasGpio1Mv();
    /**
     * <code>optional sint32 gpio1_mv = 13;</code>
     * @return The gpio1Mv.
     */
    int getGpio1Mv();

    /**
     * <code>optional bool int_gpio0 = 14;</code>
     * @return Whether the intGpio0 field is set.
     */
    boolean hasIntGpio0();
    /**
     * <code>optional bool int_gpio0 = 14;</code>
     * @return The intGpio0.
     */
    boolean getIntGpio0();

    /**
     * <code>optional bool int_gpio1 = 15;</code>
     * @return Whether the intGpio1 field is set.
     */
    boolean hasIntGpio1();
    /**
     * <code>optional bool int_gpio1 = 15;</code>
     * @return The intGpio1.
     */
    boolean getIntGpio1();

    /**
     * <code>optional bool int_acc = 16;</code>
     * @return Whether the intAcc field is set.
     */
    boolean hasIntAcc();
    /**
     * <code>optional bool int_acc = 16;</code>
     * @return The intAcc.
     */
    boolean getIntAcc();
  }
  /**
   * Protobuf type {@code com.example.lohmegalog.bb_log_entry}
   */
  public static final class bb_log_entry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.lohmegalog.bb_log_entry)
      bb_log_entryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use bb_log_entry.newBuilder() to construct.
    private bb_log_entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private bb_log_entry() {
      compass_ = emptyIntList();
      accelerometer_ = emptyIntList();
      gyro_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new bb_log_entry();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BbLogEntry.internal_static_com_example_lohmegalog_bb_log_entry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BbLogEntry.internal_static_com_example_lohmegalog_bb_log_entry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BbLogEntry.bb_log_entry.class, BbLogEntry.bb_log_entry.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timestamp_ = 0;
    /**
     * <code>required uint32 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required uint32 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public int getTimestamp() {
      return timestamp_;
    }

    public static final int PRESSURE_FIELD_NUMBER = 2;
    private int pressure_ = 0;
    /**
     * <code>optional sint32 pressure = 2;</code>
     * @return Whether the pressure field is set.
     */
    @java.lang.Override
    public boolean hasPressure() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional sint32 pressure = 2;</code>
     * @return The pressure.
     */
    @java.lang.Override
    public int getPressure() {
      return pressure_;
    }

    public static final int UVI_FIELD_NUMBER = 3;
    private int uvi_ = 0;
    /**
     * <code>optional sint32 uvi = 3;</code>
     * @return Whether the uvi field is set.
     */
    @java.lang.Override
    public boolean hasUvi() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional sint32 uvi = 3;</code>
     * @return The uvi.
     */
    @java.lang.Override
    public int getUvi() {
      return uvi_;
    }

    public static final int LUX_FIELD_NUMBER = 4;
    private int lux_ = 0;
    /**
     * <code>optional sint32 lux = 4;</code>
     * @return Whether the lux field is set.
     */
    @java.lang.Override
    public boolean hasLux() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional sint32 lux = 4;</code>
     * @return The lux.
     */
    @java.lang.Override
    public int getLux() {
      return lux_;
    }

    public static final int RH_FIELD_NUMBER = 5;
    private int rh_ = 0;
    /**
     * <code>optional sint32 rh = 5;</code>
     * @return Whether the rh field is set.
     */
    @java.lang.Override
    public boolean hasRh() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional sint32 rh = 5;</code>
     * @return The rh.
     */
    @java.lang.Override
    public int getRh() {
      return rh_;
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 6;
    private int temperature_ = 0;
    /**
     * <code>optional sint32 temperature = 6;</code>
     * @return Whether the temperature field is set.
     */
    @java.lang.Override
    public boolean hasTemperature() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional sint32 temperature = 6;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public int getTemperature() {
      return temperature_;
    }

    public static final int COMPASS_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList compass_;
    /**
     * <code>repeated sint32 compass = 7;</code>
     * @return A list containing the compass.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getCompassList() {
      return compass_;
    }
    /**
     * <code>repeated sint32 compass = 7;</code>
     * @return The count of compass.
     */
    public int getCompassCount() {
      return compass_.size();
    }
    /**
     * <code>repeated sint32 compass = 7;</code>
     * @param index The index of the element to return.
     * @return The compass at the given index.
     */
    public int getCompass(int index) {
      return compass_.getInt(index);
    }

    public static final int ACCELEROMETER_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList accelerometer_;
    /**
     * <code>repeated sint32 accelerometer = 8;</code>
     * @return A list containing the accelerometer.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getAccelerometerList() {
      return accelerometer_;
    }
    /**
     * <code>repeated sint32 accelerometer = 8;</code>
     * @return The count of accelerometer.
     */
    public int getAccelerometerCount() {
      return accelerometer_.size();
    }
    /**
     * <code>repeated sint32 accelerometer = 8;</code>
     * @param index The index of the element to return.
     * @return The accelerometer at the given index.
     */
    public int getAccelerometer(int index) {
      return accelerometer_.getInt(index);
    }

    public static final int GYRO_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList gyro_;
    /**
     * <code>repeated sint32 gyro = 9;</code>
     * @return A list containing the gyro.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getGyroList() {
      return gyro_;
    }
    /**
     * <code>repeated sint32 gyro = 9;</code>
     * @return The count of gyro.
     */
    public int getGyroCount() {
      return gyro_.size();
    }
    /**
     * <code>repeated sint32 gyro = 9;</code>
     * @param index The index of the element to return.
     * @return The gyro at the given index.
     */
    public int getGyro(int index) {
      return gyro_.getInt(index);
    }

    public static final int BATTERY_MV_FIELD_NUMBER = 11;
    private int batteryMv_ = 0;
    /**
     * <pre>
     *repeated float mpu9520_quaternion = 10;
     * </pre>
     *
     * <code>optional sint32 battery_mv = 11;</code>
     * @return Whether the batteryMv field is set.
     */
    @java.lang.Override
    public boolean hasBatteryMv() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *repeated float mpu9520_quaternion = 10;
     * </pre>
     *
     * <code>optional sint32 battery_mv = 11;</code>
     * @return The batteryMv.
     */
    @java.lang.Override
    public int getBatteryMv() {
      return batteryMv_;
    }

    public static final int GPIO0_MV_FIELD_NUMBER = 12;
    private int gpio0Mv_ = 0;
    /**
     * <code>optional sint32 gpio0_mv = 12;</code>
     * @return Whether the gpio0Mv field is set.
     */
    @java.lang.Override
    public boolean hasGpio0Mv() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional sint32 gpio0_mv = 12;</code>
     * @return The gpio0Mv.
     */
    @java.lang.Override
    public int getGpio0Mv() {
      return gpio0Mv_;
    }

    public static final int GPIO1_MV_FIELD_NUMBER = 13;
    private int gpio1Mv_ = 0;
    /**
     * <code>optional sint32 gpio1_mv = 13;</code>
     * @return Whether the gpio1Mv field is set.
     */
    @java.lang.Override
    public boolean hasGpio1Mv() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional sint32 gpio1_mv = 13;</code>
     * @return The gpio1Mv.
     */
    @java.lang.Override
    public int getGpio1Mv() {
      return gpio1Mv_;
    }

    public static final int INT_GPIO0_FIELD_NUMBER = 14;
    private boolean intGpio0_ = false;
    /**
     * <code>optional bool int_gpio0 = 14;</code>
     * @return Whether the intGpio0 field is set.
     */
    @java.lang.Override
    public boolean hasIntGpio0() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional bool int_gpio0 = 14;</code>
     * @return The intGpio0.
     */
    @java.lang.Override
    public boolean getIntGpio0() {
      return intGpio0_;
    }

    public static final int INT_GPIO1_FIELD_NUMBER = 15;
    private boolean intGpio1_ = false;
    /**
     * <code>optional bool int_gpio1 = 15;</code>
     * @return Whether the intGpio1 field is set.
     */
    @java.lang.Override
    public boolean hasIntGpio1() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional bool int_gpio1 = 15;</code>
     * @return The intGpio1.
     */
    @java.lang.Override
    public boolean getIntGpio1() {
      return intGpio1_;
    }

    public static final int INT_ACC_FIELD_NUMBER = 16;
    private boolean intAcc_ = false;
    /**
     * <code>optional bool int_acc = 16;</code>
     * @return Whether the intAcc field is set.
     */
    @java.lang.Override
    public boolean hasIntAcc() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional bool int_acc = 16;</code>
     * @return The intAcc.
     */
    @java.lang.Override
    public boolean getIntAcc() {
      return intAcc_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeSInt32(2, pressure_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeSInt32(3, uvi_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeSInt32(4, lux_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeSInt32(5, rh_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeSInt32(6, temperature_);
      }
      for (int i = 0; i < compass_.size(); i++) {
        output.writeSInt32(7, compass_.getInt(i));
      }
      for (int i = 0; i < accelerometer_.size(); i++) {
        output.writeSInt32(8, accelerometer_.getInt(i));
      }
      for (int i = 0; i < gyro_.size(); i++) {
        output.writeSInt32(9, gyro_.getInt(i));
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeSInt32(11, batteryMv_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeSInt32(12, gpio0Mv_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeSInt32(13, gpio1Mv_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeBool(14, intGpio0_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeBool(15, intGpio1_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        output.writeBool(16, intAcc_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, pressure_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, uvi_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, lux_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(5, rh_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(6, temperature_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < compass_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeSInt32SizeNoTag(compass_.getInt(i));
        }
        size += dataSize;
        size += 1 * getCompassList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < accelerometer_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeSInt32SizeNoTag(accelerometer_.getInt(i));
        }
        size += dataSize;
        size += 1 * getAccelerometerList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < gyro_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeSInt32SizeNoTag(gyro_.getInt(i));
        }
        size += dataSize;
        size += 1 * getGyroList().size();
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(11, batteryMv_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(12, gpio0Mv_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(13, gpio1Mv_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, intGpio0_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(15, intGpio1_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(16, intAcc_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BbLogEntry.bb_log_entry)) {
        return super.equals(obj);
      }
      BbLogEntry.bb_log_entry other = (BbLogEntry.bb_log_entry) obj;

      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (hasPressure() != other.hasPressure()) return false;
      if (hasPressure()) {
        if (getPressure()
            != other.getPressure()) return false;
      }
      if (hasUvi() != other.hasUvi()) return false;
      if (hasUvi()) {
        if (getUvi()
            != other.getUvi()) return false;
      }
      if (hasLux() != other.hasLux()) return false;
      if (hasLux()) {
        if (getLux()
            != other.getLux()) return false;
      }
      if (hasRh() != other.hasRh()) return false;
      if (hasRh()) {
        if (getRh()
            != other.getRh()) return false;
      }
      if (hasTemperature() != other.hasTemperature()) return false;
      if (hasTemperature()) {
        if (getTemperature()
            != other.getTemperature()) return false;
      }
      if (!getCompassList()
          .equals(other.getCompassList())) return false;
      if (!getAccelerometerList()
          .equals(other.getAccelerometerList())) return false;
      if (!getGyroList()
          .equals(other.getGyroList())) return false;
      if (hasBatteryMv() != other.hasBatteryMv()) return false;
      if (hasBatteryMv()) {
        if (getBatteryMv()
            != other.getBatteryMv()) return false;
      }
      if (hasGpio0Mv() != other.hasGpio0Mv()) return false;
      if (hasGpio0Mv()) {
        if (getGpio0Mv()
            != other.getGpio0Mv()) return false;
      }
      if (hasGpio1Mv() != other.hasGpio1Mv()) return false;
      if (hasGpio1Mv()) {
        if (getGpio1Mv()
            != other.getGpio1Mv()) return false;
      }
      if (hasIntGpio0() != other.hasIntGpio0()) return false;
      if (hasIntGpio0()) {
        if (getIntGpio0()
            != other.getIntGpio0()) return false;
      }
      if (hasIntGpio1() != other.hasIntGpio1()) return false;
      if (hasIntGpio1()) {
        if (getIntGpio1()
            != other.getIntGpio1()) return false;
      }
      if (hasIntAcc() != other.hasIntAcc()) return false;
      if (hasIntAcc()) {
        if (getIntAcc()
            != other.getIntAcc()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp();
      }
      if (hasPressure()) {
        hash = (37 * hash) + PRESSURE_FIELD_NUMBER;
        hash = (53 * hash) + getPressure();
      }
      if (hasUvi()) {
        hash = (37 * hash) + UVI_FIELD_NUMBER;
        hash = (53 * hash) + getUvi();
      }
      if (hasLux()) {
        hash = (37 * hash) + LUX_FIELD_NUMBER;
        hash = (53 * hash) + getLux();
      }
      if (hasRh()) {
        hash = (37 * hash) + RH_FIELD_NUMBER;
        hash = (53 * hash) + getRh();
      }
      if (hasTemperature()) {
        hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
        hash = (53 * hash) + getTemperature();
      }
      if (getCompassCount() > 0) {
        hash = (37 * hash) + COMPASS_FIELD_NUMBER;
        hash = (53 * hash) + getCompassList().hashCode();
      }
      if (getAccelerometerCount() > 0) {
        hash = (37 * hash) + ACCELEROMETER_FIELD_NUMBER;
        hash = (53 * hash) + getAccelerometerList().hashCode();
      }
      if (getGyroCount() > 0) {
        hash = (37 * hash) + GYRO_FIELD_NUMBER;
        hash = (53 * hash) + getGyroList().hashCode();
      }
      if (hasBatteryMv()) {
        hash = (37 * hash) + BATTERY_MV_FIELD_NUMBER;
        hash = (53 * hash) + getBatteryMv();
      }
      if (hasGpio0Mv()) {
        hash = (37 * hash) + GPIO0_MV_FIELD_NUMBER;
        hash = (53 * hash) + getGpio0Mv();
      }
      if (hasGpio1Mv()) {
        hash = (37 * hash) + GPIO1_MV_FIELD_NUMBER;
        hash = (53 * hash) + getGpio1Mv();
      }
      if (hasIntGpio0()) {
        hash = (37 * hash) + INT_GPIO0_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIntGpio0());
      }
      if (hasIntGpio1()) {
        hash = (37 * hash) + INT_GPIO1_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIntGpio1());
      }
      if (hasIntAcc()) {
        hash = (37 * hash) + INT_ACC_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIntAcc());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BbLogEntry.bb_log_entry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BbLogEntry.bb_log_entry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BbLogEntry.bb_log_entry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BbLogEntry.bb_log_entry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BbLogEntry.bb_log_entry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BbLogEntry.bb_log_entry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BbLogEntry.bb_log_entry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BbLogEntry.bb_log_entry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BbLogEntry.bb_log_entry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BbLogEntry.bb_log_entry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BbLogEntry.bb_log_entry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BbLogEntry.bb_log_entry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BbLogEntry.bb_log_entry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.lohmegalog.bb_log_entry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.lohmegalog.bb_log_entry)
        BbLogEntry.bb_log_entryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BbLogEntry.internal_static_com_example_lohmegalog_bb_log_entry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BbLogEntry.internal_static_com_example_lohmegalog_bb_log_entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BbLogEntry.bb_log_entry.class, BbLogEntry.bb_log_entry.Builder.class);
      }

      // Construct using com.example.lohmegalog.BbLogEntry.bb_log_entry.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestamp_ = 0;
        pressure_ = 0;
        uvi_ = 0;
        lux_ = 0;
        rh_ = 0;
        temperature_ = 0;
        compass_ = emptyIntList();
        accelerometer_ = emptyIntList();
        gyro_ = emptyIntList();
        batteryMv_ = 0;
        gpio0Mv_ = 0;
        gpio1Mv_ = 0;
        intGpio0_ = false;
        intGpio1_ = false;
        intAcc_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BbLogEntry.internal_static_com_example_lohmegalog_bb_log_entry_descriptor;
      }

      @java.lang.Override
      public BbLogEntry.bb_log_entry getDefaultInstanceForType() {
        return BbLogEntry.bb_log_entry.getDefaultInstance();
      }

      @java.lang.Override
      public BbLogEntry.bb_log_entry build() {
        BbLogEntry.bb_log_entry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public BbLogEntry.bb_log_entry buildPartial() {
        BbLogEntry.bb_log_entry result = new BbLogEntry.bb_log_entry(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(BbLogEntry.bb_log_entry result) {
        if (((bitField0_ & 0x00000040) != 0)) {
          compass_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.compass_ = compass_;
        if (((bitField0_ & 0x00000080) != 0)) {
          accelerometer_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.accelerometer_ = accelerometer_;
        if (((bitField0_ & 0x00000100) != 0)) {
          gyro_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.gyro_ = gyro_;
      }

      private void buildPartial0(BbLogEntry.bb_log_entry result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.pressure_ = pressure_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.uvi_ = uvi_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.lux_ = lux_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.rh_ = rh_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.temperature_ = temperature_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.batteryMv_ = batteryMv_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.gpio0Mv_ = gpio0Mv_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.gpio1Mv_ = gpio1Mv_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.intGpio0_ = intGpio0_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.intGpio1_ = intGpio1_;
          to_bitField0_ |= 0x00000400;
        }
        if (((from_bitField0_ & 0x00004000) != 0)) {
          result.intAcc_ = intAcc_;
          to_bitField0_ |= 0x00000800;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BbLogEntry.bb_log_entry) {
          return mergeFrom((BbLogEntry.bb_log_entry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BbLogEntry.bb_log_entry other) {
        if (other == BbLogEntry.bb_log_entry.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasPressure()) {
          setPressure(other.getPressure());
        }
        if (other.hasUvi()) {
          setUvi(other.getUvi());
        }
        if (other.hasLux()) {
          setLux(other.getLux());
        }
        if (other.hasRh()) {
          setRh(other.getRh());
        }
        if (other.hasTemperature()) {
          setTemperature(other.getTemperature());
        }
        if (!other.compass_.isEmpty()) {
          if (compass_.isEmpty()) {
            compass_ = other.compass_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureCompassIsMutable();
            compass_.addAll(other.compass_);
          }
          onChanged();
        }
        if (!other.accelerometer_.isEmpty()) {
          if (accelerometer_.isEmpty()) {
            accelerometer_ = other.accelerometer_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureAccelerometerIsMutable();
            accelerometer_.addAll(other.accelerometer_);
          }
          onChanged();
        }
        if (!other.gyro_.isEmpty()) {
          if (gyro_.isEmpty()) {
            gyro_ = other.gyro_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureGyroIsMutable();
            gyro_.addAll(other.gyro_);
          }
          onChanged();
        }
        if (other.hasBatteryMv()) {
          setBatteryMv(other.getBatteryMv());
        }
        if (other.hasGpio0Mv()) {
          setGpio0Mv(other.getGpio0Mv());
        }
        if (other.hasGpio1Mv()) {
          setGpio1Mv(other.getGpio1Mv());
        }
        if (other.hasIntGpio0()) {
          setIntGpio0(other.getIntGpio0());
        }
        if (other.hasIntGpio1()) {
          setIntGpio1(other.getIntGpio1());
        }
        if (other.hasIntAcc()) {
          setIntAcc(other.getIntAcc());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestamp_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                pressure_ = input.readSInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                uvi_ = input.readSInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                lux_ = input.readSInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                rh_ = input.readSInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                temperature_ = input.readSInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                int v = input.readSInt32();
                ensureCompassIsMutable();
                compass_.addInt(v);
                break;
              } // case 56
              case 58: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureCompassIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  compass_.addInt(input.readSInt32());
                }
                input.popLimit(limit);
                break;
              } // case 58
              case 64: {
                int v = input.readSInt32();
                ensureAccelerometerIsMutable();
                accelerometer_.addInt(v);
                break;
              } // case 64
              case 66: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureAccelerometerIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  accelerometer_.addInt(input.readSInt32());
                }
                input.popLimit(limit);
                break;
              } // case 66
              case 72: {
                int v = input.readSInt32();
                ensureGyroIsMutable();
                gyro_.addInt(v);
                break;
              } // case 72
              case 74: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureGyroIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  gyro_.addInt(input.readSInt32());
                }
                input.popLimit(limit);
                break;
              } // case 74
              case 88: {
                batteryMv_ = input.readSInt32();
                bitField0_ |= 0x00000200;
                break;
              } // case 88
              case 96: {
                gpio0Mv_ = input.readSInt32();
                bitField0_ |= 0x00000400;
                break;
              } // case 96
              case 104: {
                gpio1Mv_ = input.readSInt32();
                bitField0_ |= 0x00000800;
                break;
              } // case 104
              case 112: {
                intGpio0_ = input.readBool();
                bitField0_ |= 0x00001000;
                break;
              } // case 112
              case 120: {
                intGpio1_ = input.readBool();
                bitField0_ |= 0x00002000;
                break;
              } // case 120
              case 128: {
                intAcc_ = input.readBool();
                bitField0_ |= 0x00004000;
                break;
              } // case 128
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int timestamp_ ;
      /**
       * <code>required uint32 timestamp = 1;</code>
       * @return Whether the timestamp field is set.
       */
      @java.lang.Override
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required uint32 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint32 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(int value) {

        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0;
        onChanged();
        return this;
      }

      private int pressure_ ;
      /**
       * <code>optional sint32 pressure = 2;</code>
       * @return Whether the pressure field is set.
       */
      @java.lang.Override
      public boolean hasPressure() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional sint32 pressure = 2;</code>
       * @return The pressure.
       */
      @java.lang.Override
      public int getPressure() {
        return pressure_;
      }
      /**
       * <code>optional sint32 pressure = 2;</code>
       * @param value The pressure to set.
       * @return This builder for chaining.
       */
      public Builder setPressure(int value) {

        pressure_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 pressure = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPressure() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pressure_ = 0;
        onChanged();
        return this;
      }

      private int uvi_ ;
      /**
       * <code>optional sint32 uvi = 3;</code>
       * @return Whether the uvi field is set.
       */
      @java.lang.Override
      public boolean hasUvi() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional sint32 uvi = 3;</code>
       * @return The uvi.
       */
      @java.lang.Override
      public int getUvi() {
        return uvi_;
      }
      /**
       * <code>optional sint32 uvi = 3;</code>
       * @param value The uvi to set.
       * @return This builder for chaining.
       */
      public Builder setUvi(int value) {

        uvi_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 uvi = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUvi() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uvi_ = 0;
        onChanged();
        return this;
      }

      private int lux_ ;
      /**
       * <code>optional sint32 lux = 4;</code>
       * @return Whether the lux field is set.
       */
      @java.lang.Override
      public boolean hasLux() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional sint32 lux = 4;</code>
       * @return The lux.
       */
      @java.lang.Override
      public int getLux() {
        return lux_;
      }
      /**
       * <code>optional sint32 lux = 4;</code>
       * @param value The lux to set.
       * @return This builder for chaining.
       */
      public Builder setLux(int value) {

        lux_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 lux = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLux() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lux_ = 0;
        onChanged();
        return this;
      }

      private int rh_ ;
      /**
       * <code>optional sint32 rh = 5;</code>
       * @return Whether the rh field is set.
       */
      @java.lang.Override
      public boolean hasRh() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional sint32 rh = 5;</code>
       * @return The rh.
       */
      @java.lang.Override
      public int getRh() {
        return rh_;
      }
      /**
       * <code>optional sint32 rh = 5;</code>
       * @param value The rh to set.
       * @return This builder for chaining.
       */
      public Builder setRh(int value) {

        rh_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 rh = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRh() {
        bitField0_ = (bitField0_ & ~0x00000010);
        rh_ = 0;
        onChanged();
        return this;
      }

      private int temperature_ ;
      /**
       * <code>optional sint32 temperature = 6;</code>
       * @return Whether the temperature field is set.
       */
      @java.lang.Override
      public boolean hasTemperature() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional sint32 temperature = 6;</code>
       * @return The temperature.
       */
      @java.lang.Override
      public int getTemperature() {
        return temperature_;
      }
      /**
       * <code>optional sint32 temperature = 6;</code>
       * @param value The temperature to set.
       * @return This builder for chaining.
       */
      public Builder setTemperature(int value) {

        temperature_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 temperature = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemperature() {
        bitField0_ = (bitField0_ & ~0x00000020);
        temperature_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList compass_ = emptyIntList();
      private void ensureCompassIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          compass_ = mutableCopy(compass_);
          bitField0_ |= 0x00000040;
        }
      }
      /**
       * <code>repeated sint32 compass = 7;</code>
       * @return A list containing the compass.
       */
      public java.util.List<java.lang.Integer>
          getCompassList() {
        return ((bitField0_ & 0x00000040) != 0) ?
                 java.util.Collections.unmodifiableList(compass_) : compass_;
      }
      /**
       * <code>repeated sint32 compass = 7;</code>
       * @return The count of compass.
       */
      public int getCompassCount() {
        return compass_.size();
      }
      /**
       * <code>repeated sint32 compass = 7;</code>
       * @param index The index of the element to return.
       * @return The compass at the given index.
       */
      public int getCompass(int index) {
        return compass_.getInt(index);
      }
      /**
       * <code>repeated sint32 compass = 7;</code>
       * @param index The index to set the value at.
       * @param value The compass to set.
       * @return This builder for chaining.
       */
      public Builder setCompass(
          int index, int value) {

        ensureCompassIsMutable();
        compass_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 compass = 7;</code>
       * @param value The compass to add.
       * @return This builder for chaining.
       */
      public Builder addCompass(int value) {

        ensureCompassIsMutable();
        compass_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 compass = 7;</code>
       * @param values The compass to add.
       * @return This builder for chaining.
       */
      public Builder addAllCompass(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureCompassIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, compass_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 compass = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompass() {
        compass_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList accelerometer_ = emptyIntList();
      private void ensureAccelerometerIsMutable() {
        if (!((bitField0_ & 0x00000080) != 0)) {
          accelerometer_ = mutableCopy(accelerometer_);
          bitField0_ |= 0x00000080;
        }
      }
      /**
       * <code>repeated sint32 accelerometer = 8;</code>
       * @return A list containing the accelerometer.
       */
      public java.util.List<java.lang.Integer>
          getAccelerometerList() {
        return ((bitField0_ & 0x00000080) != 0) ?
                 java.util.Collections.unmodifiableList(accelerometer_) : accelerometer_;
      }
      /**
       * <code>repeated sint32 accelerometer = 8;</code>
       * @return The count of accelerometer.
       */
      public int getAccelerometerCount() {
        return accelerometer_.size();
      }
      /**
       * <code>repeated sint32 accelerometer = 8;</code>
       * @param index The index of the element to return.
       * @return The accelerometer at the given index.
       */
      public int getAccelerometer(int index) {
        return accelerometer_.getInt(index);
      }
      /**
       * <code>repeated sint32 accelerometer = 8;</code>
       * @param index The index to set the value at.
       * @param value The accelerometer to set.
       * @return This builder for chaining.
       */
      public Builder setAccelerometer(
          int index, int value) {

        ensureAccelerometerIsMutable();
        accelerometer_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 accelerometer = 8;</code>
       * @param value The accelerometer to add.
       * @return This builder for chaining.
       */
      public Builder addAccelerometer(int value) {

        ensureAccelerometerIsMutable();
        accelerometer_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 accelerometer = 8;</code>
       * @param values The accelerometer to add.
       * @return This builder for chaining.
       */
      public Builder addAllAccelerometer(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAccelerometerIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, accelerometer_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 accelerometer = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccelerometer() {
        accelerometer_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList gyro_ = emptyIntList();
      private void ensureGyroIsMutable() {
        if (!((bitField0_ & 0x00000100) != 0)) {
          gyro_ = mutableCopy(gyro_);
          bitField0_ |= 0x00000100;
        }
      }
      /**
       * <code>repeated sint32 gyro = 9;</code>
       * @return A list containing the gyro.
       */
      public java.util.List<java.lang.Integer>
          getGyroList() {
        return ((bitField0_ & 0x00000100) != 0) ?
                 java.util.Collections.unmodifiableList(gyro_) : gyro_;
      }
      /**
       * <code>repeated sint32 gyro = 9;</code>
       * @return The count of gyro.
       */
      public int getGyroCount() {
        return gyro_.size();
      }
      /**
       * <code>repeated sint32 gyro = 9;</code>
       * @param index The index of the element to return.
       * @return The gyro at the given index.
       */
      public int getGyro(int index) {
        return gyro_.getInt(index);
      }
      /**
       * <code>repeated sint32 gyro = 9;</code>
       * @param index The index to set the value at.
       * @param value The gyro to set.
       * @return This builder for chaining.
       */
      public Builder setGyro(
          int index, int value) {

        ensureGyroIsMutable();
        gyro_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 gyro = 9;</code>
       * @param value The gyro to add.
       * @return This builder for chaining.
       */
      public Builder addGyro(int value) {

        ensureGyroIsMutable();
        gyro_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 gyro = 9;</code>
       * @param values The gyro to add.
       * @return This builder for chaining.
       */
      public Builder addAllGyro(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureGyroIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, gyro_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated sint32 gyro = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearGyro() {
        gyro_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }

      private int batteryMv_ ;
      /**
       * <pre>
       *repeated float mpu9520_quaternion = 10;
       * </pre>
       *
       * <code>optional sint32 battery_mv = 11;</code>
       * @return Whether the batteryMv field is set.
       */
      @java.lang.Override
      public boolean hasBatteryMv() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <pre>
       *repeated float mpu9520_quaternion = 10;
       * </pre>
       *
       * <code>optional sint32 battery_mv = 11;</code>
       * @return The batteryMv.
       */
      @java.lang.Override
      public int getBatteryMv() {
        return batteryMv_;
      }
      /**
       * <pre>
       *repeated float mpu9520_quaternion = 10;
       * </pre>
       *
       * <code>optional sint32 battery_mv = 11;</code>
       * @param value The batteryMv to set.
       * @return This builder for chaining.
       */
      public Builder setBatteryMv(int value) {

        batteryMv_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *repeated float mpu9520_quaternion = 10;
       * </pre>
       *
       * <code>optional sint32 battery_mv = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatteryMv() {
        bitField0_ = (bitField0_ & ~0x00000200);
        batteryMv_ = 0;
        onChanged();
        return this;
      }

      private int gpio0Mv_ ;
      /**
       * <code>optional sint32 gpio0_mv = 12;</code>
       * @return Whether the gpio0Mv field is set.
       */
      @java.lang.Override
      public boolean hasGpio0Mv() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>optional sint32 gpio0_mv = 12;</code>
       * @return The gpio0Mv.
       */
      @java.lang.Override
      public int getGpio0Mv() {
        return gpio0Mv_;
      }
      /**
       * <code>optional sint32 gpio0_mv = 12;</code>
       * @param value The gpio0Mv to set.
       * @return This builder for chaining.
       */
      public Builder setGpio0Mv(int value) {

        gpio0Mv_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 gpio0_mv = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearGpio0Mv() {
        bitField0_ = (bitField0_ & ~0x00000400);
        gpio0Mv_ = 0;
        onChanged();
        return this;
      }

      private int gpio1Mv_ ;
      /**
       * <code>optional sint32 gpio1_mv = 13;</code>
       * @return Whether the gpio1Mv field is set.
       */
      @java.lang.Override
      public boolean hasGpio1Mv() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>optional sint32 gpio1_mv = 13;</code>
       * @return The gpio1Mv.
       */
      @java.lang.Override
      public int getGpio1Mv() {
        return gpio1Mv_;
      }
      /**
       * <code>optional sint32 gpio1_mv = 13;</code>
       * @param value The gpio1Mv to set.
       * @return This builder for chaining.
       */
      public Builder setGpio1Mv(int value) {

        gpio1Mv_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 gpio1_mv = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearGpio1Mv() {
        bitField0_ = (bitField0_ & ~0x00000800);
        gpio1Mv_ = 0;
        onChanged();
        return this;
      }

      private boolean intGpio0_ ;
      /**
       * <code>optional bool int_gpio0 = 14;</code>
       * @return Whether the intGpio0 field is set.
       */
      @java.lang.Override
      public boolean hasIntGpio0() {
        return ((bitField0_ & 0x00001000) != 0);
      }
      /**
       * <code>optional bool int_gpio0 = 14;</code>
       * @return The intGpio0.
       */
      @java.lang.Override
      public boolean getIntGpio0() {
        return intGpio0_;
      }
      /**
       * <code>optional bool int_gpio0 = 14;</code>
       * @param value The intGpio0 to set.
       * @return This builder for chaining.
       */
      public Builder setIntGpio0(boolean value) {

        intGpio0_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool int_gpio0 = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntGpio0() {
        bitField0_ = (bitField0_ & ~0x00001000);
        intGpio0_ = false;
        onChanged();
        return this;
      }

      private boolean intGpio1_ ;
      /**
       * <code>optional bool int_gpio1 = 15;</code>
       * @return Whether the intGpio1 field is set.
       */
      @java.lang.Override
      public boolean hasIntGpio1() {
        return ((bitField0_ & 0x00002000) != 0);
      }
      /**
       * <code>optional bool int_gpio1 = 15;</code>
       * @return The intGpio1.
       */
      @java.lang.Override
      public boolean getIntGpio1() {
        return intGpio1_;
      }
      /**
       * <code>optional bool int_gpio1 = 15;</code>
       * @param value The intGpio1 to set.
       * @return This builder for chaining.
       */
      public Builder setIntGpio1(boolean value) {

        intGpio1_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool int_gpio1 = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntGpio1() {
        bitField0_ = (bitField0_ & ~0x00002000);
        intGpio1_ = false;
        onChanged();
        return this;
      }

      private boolean intAcc_ ;
      /**
       * <code>optional bool int_acc = 16;</code>
       * @return Whether the intAcc field is set.
       */
      @java.lang.Override
      public boolean hasIntAcc() {
        return ((bitField0_ & 0x00004000) != 0);
      }
      /**
       * <code>optional bool int_acc = 16;</code>
       * @return The intAcc.
       */
      @java.lang.Override
      public boolean getIntAcc() {
        return intAcc_;
      }
      /**
       * <code>optional bool int_acc = 16;</code>
       * @param value The intAcc to set.
       * @return This builder for chaining.
       */
      public Builder setIntAcc(boolean value) {

        intAcc_ = value;
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool int_acc = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntAcc() {
        bitField0_ = (bitField0_ & ~0x00004000);
        intAcc_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.lohmegalog.bb_log_entry)
    }

    // @@protoc_insertion_point(class_scope:com.example.lohmegalog.bb_log_entry)
    private static final BbLogEntry.bb_log_entry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BbLogEntry.bb_log_entry();
    }

    public static BbLogEntry.bb_log_entry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<bb_log_entry>
        PARSER = new com.google.protobuf.AbstractParser<bb_log_entry>() {
      @java.lang.Override
      public bb_log_entry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<bb_log_entry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<bb_log_entry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public BbLogEntry.bb_log_entry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_lohmegalog_bb_log_entry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_lohmegalog_bb_log_entry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%app/src/main/proto/bb_log_entry.proto\022" +
      "\026com.example.lohmegalog\"\223\002\n\014bb_log_entry" +
      "\022\021\n\ttimestamp\030\001 \002(\r\022\020\n\010pressure\030\002 \001(\021\022\013\n" +
      "\003uvi\030\003 \001(\021\022\013\n\003lux\030\004 \001(\021\022\n\n\002rh\030\005 \001(\021\022\023\n\013t" +
      "emperature\030\006 \001(\021\022\017\n\007compass\030\007 \003(\021\022\025\n\racc" +
      "elerometer\030\010 \003(\021\022\014\n\004gyro\030\t \003(\021\022\022\n\nbatter" +
      "y_mv\030\013 \001(\021\022\020\n\010gpio0_mv\030\014 \001(\021\022\020\n\010gpio1_mv" +
      "\030\r \001(\021\022\021\n\tint_gpio0\030\016 \001(\010\022\021\n\tint_gpio1\030\017" +
      " \001(\010\022\017\n\007int_acc\030\020 \001(\010"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_lohmegalog_bb_log_entry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_lohmegalog_bb_log_entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_lohmegalog_bb_log_entry_descriptor,
        new java.lang.String[] { "Timestamp", "Pressure", "Uvi", "Lux", "Rh", "Temperature", "Compass", "Accelerometer", "Gyro", "BatteryMv", "Gpio0Mv", "Gpio1Mv", "IntGpio0", "IntGpio1", "IntAcc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
