// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: app/src/main/proto/bb_log_entry.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.lohmegalog.protobuf;

